FROM python:3.14-slim

# prvents wierd cache issues
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# just necessary dependencies
COPY requirements.api.txt .
RUN pip install --no-cache-dir -r requirements.api.txt

# Project's code
COPY src ./src

EXPOSE 8000

CMD [ "uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000" ]