class DQSeverity:
    ERROR = "ERROR"
    WARNING = "WARNING"

class DQIssueCode:
    MISSING_INVOICE_ID = "MISSING_INVOICE_ID"
    INVALID_NUMERIC = "INVALID_NUMERIC"
    INVALID_DATE = "INVALID_DATE"
    FALLBACK_EVENT_DATE = "FALLBACK_EVENT_DATE"
    TEST_DQ = "TEST_DQ"
    SIGN_MISMATCH_QTY_AMOUNT = "SIGN_MISMATCH_QTY_AMOUNT"
    NEGATIVE_QTY_ON_SALE = "NEGATIVE_QTY_ON_SALE"
    POSITIVE_QTY_ON_RETURN = "POSITIVE_QTY_ON_RETURN"

