class DQSeverity:
    ERROR = "ERROR"
    WARNING = "WARNING"

class DQIssueCode:
    MISSING_INVOICE_ID = "MISSING_INVOICE_ID"
    INVALID_NUMERIC = "INVALID_NUMERIC"
    INVALID_DATE = "INVALID_DATE"
    FALLBACK_EVENT_DATE = "FALLBACK_EVENT_DATE"
    TEST_DQ = "TEST_DQ"
